// <auto-generated />
namespace PonyRidesWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlteredBooking2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteredBooking2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605250747495_AlteredBooking2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
